# Generated by Django 3.2.12 on 2025-09-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Hidromiel', max_length=100)),
                ('volumen', models.FloatField()),
                ('og', models.FloatField()),
                ('tipo_miel', models.CharField(max_length=50)),
                ('levadura', models.CharField(max_length=50)),
                ('eficiencia', models.FloatField()),
                ('especias', models.CharField(blank=True, max_length=50, null=True)),
                ('frutas', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_frutas', models.FloatField(default=0)),
                ('bloqueador', models.CharField(max_length=10)),
                ('tipo_bloqueador', models.CharField(max_length=50)),
                ('nutrientes', models.CharField(max_length=10)),
                ('tipo_nutrientes', models.CharField(max_length=50)),
                ('clarificante', models.CharField(max_length=10)),
                ('tipo_clarificante', models.CharField(max_length=50)),
                ('temperatura', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
