# Generated by Django 5.2.6 on 2025-09-15 00:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='bloqueador',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad_frutas',
            field=models.FloatField(default=0, help_text='Cantidad de frutas en gramos', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='clarificante',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='duracion',
            field=models.IntegerField(help_text='Duración en días (1-365)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='eficiencia',
            field=models.FloatField(help_text='Eficiencia en porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='especias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='frutas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='levadura',
            field=models.CharField(help_text='Tipo de levadura utilizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='nutrientes',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='og',
            field=models.FloatField(help_text='Densidad original (1.000-1.200)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.2)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH (2.0-7.0)', null=True, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(7.0)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='temperatura',
            field=models.FloatField(help_text='Temperatura en °C (10-35)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_bloqueador',
            field=models.CharField(choices=[('metabisulfito', 'Metabisulfito'), ('sorbato', 'Sorbato de potasio'), ('ninguno', 'Ninguno')], default='ninguno', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_clarificante',
            field=models.CharField(choices=[('bentonita', 'Bentonita'), ('gelatina', 'Gelatina'), ('ninguno', 'Ninguno')], default='ninguno', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_miel',
            field=models.CharField(choices=[('multifloral', 'Multifloral'), ('eucalipto', 'Eucalipto'), ('acacia', 'Acacia'), ('naranjo', 'Naranjo'), ('castaño', 'Castaño'), ('romero', 'Romero'), ('otros', 'Otros')], default='multifloral', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_nutrientes',
            field=models.CharField(choices=[('dap', 'DAP'), ('fermaid', 'Fermaid'), ('ninguno', 'Ninguno')], default='ninguno', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='volumen',
            field=models.FloatField(help_text='Volumen en litros (1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
