# Generated by Django 5.2.6 on 2026-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_receta_options_receta_notas_receta_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='tipo_clarificante',
            field=models.CharField(choices=[('bentonita', 'Bentonita'), ('gelatina', 'Gelatina'), ('silica', 'Sílice'), ('ninguno', 'Ninguno')], default='ninguno', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_miel',
            field=models.CharField(choices=[('multifloral', 'Multifloral'), ('eucalipto', 'Eucalipto'), ('acacia', 'Acacia'), ('naranjo', 'Naranjo'), ('castaño', 'Castaño'), ('romero', 'Romero'), ('lavanda', 'Lavanda'), ('manuka', 'Manuka'), ('silvestre', 'Silvestre'), ('otros', 'Otros')], default='multifloral', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_nutrientes',
            field=models.CharField(choices=[('dap', 'DAP'), ('fermaid', 'Fermaid'), ('fermaidk', 'Fermaid K'), ('goferit', 'GoFerm IT'), ('ninguno', 'Ninguno')], default='ninguno', max_length=50),
        ),
    ]
